// React and Next.js
import type { Metadata } from 'next';

// Material-UI components
import { Box } from '@mui/material';

// Custom components
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

// Provider
import { AuthProvider } from '@/context/AuthContext';
import { ThemeProvider } from '@/context/ThemeContext';

export const metadata: Metadata = {
    title: 'RiCourse',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang='vi'>
            <body style={{ margin: 0 }}>
                <AuthProvider>
                    <ThemeProvider>
                        <Box
                            sx={{
                                display: 'flex',
                                flexDirection: 'column',
                                minHeight: '100vh',
                                backgroundColor: 'background.default',
                            }}
                        >
                            <Header />
                            <Box sx={{ flex: 1, mt: 16, mb: 8 }}>
                                {children}
                            </Box>
                            <Footer />
                        </Box>
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
