import type { Metadata } from "next";

import { ThemeProvider } from '@mui/material/styles';
import { Box } from "@mui/material";

import theme from '../styles/theme';
import '../styles/styles.css';

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "RiCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <ThemeProvider theme={theme}>
          <Box
            sx={{
              backgroundColor: 'background.default',
              minHeight: '100vh'
            }}
          >
            <Header />
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
