name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Cài đặt dependencies
      - name: Install dependencies
        run: |
          cd src/frontend
          npm install

      # Tạo file .env chung
      - name: Create .env
        run: |
          echo "DB_USER=username" >> src/.env
          echo "DB_PASSWORD=password" >> src/.env
          echo "DB_NAME=db" >> src/.env
          echo "DB_PORT=5432" >> src/.env
          echo "FE_PORT=3000" >> src/.env
          echo "BE_PORT=3123" >> src/.env

      # Tạo file .env cho frontend
      - name: Create Frontend .env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET || 'default_jwt_secret' }}" > ./src/frontend/.env
          echo "SIGN_UP_SECRET=${{ secrets.SIGN_UP_SECRET || 'default_sign_up_secret' }}" >> ./src/frontend/.env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api' }}" >> ./src/frontend/.env
          echo "API_DESTINATION=${{ secrets.API_DESTINATION || 'http://localhost:3123' }}" >> ./src/frontend/.env
          echo "CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL || 'http://localhost:3000' }}" >> ./src/frontend/.env

      # Tạo file .env cho backend
      - name: Create Backend .env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET || 'default_jwt_secret' }}" > ./src/frontend/.env
          echo "SIGN_UP_SECRET=${{ secrets.SIGN_UP_SECRET || 'default_sign_up_secret' }}" >> ./src/frontend/.env
          echo "DATABASE_URL=postgresql://username:password@db:5432/db" >> ./src/backend/.env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> ./src/backend/.env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> ./src/backend/.env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> ./src/backend/.env

      # Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Thiết lập Docker Compose
      - name: Set up Docker Compose
        run: |
          cd src
          docker-compose up

      # Chờ ứng dụng sẵn sàng
      - name: Wait for app to be ready
        run: |
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for the app to start..."
            sleep 5
          done

      # Chạy kiểm thử Cypress
      - name: Run Cypress tests
        run: |
          cd src/frontend
          npx cypress run

      # Dừng Docker containers
      - name: Shut down containers
        run: |
          cd src
          docker-compose down
