name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

     - name: Create Backend .env
       run: |
          mkdir -p ./frontend
          echo "JWT_SECRET=${{ secrets.FE_JWT_SECRET }}" >> ./frontend/.env
          echo "SIGN_UP_SECRET=${{ secrets.FE_SIGN_UP_SECRET }}" >> ./frontend/.env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.FE_NEXT_PUBLIC_API_URL }}" >> ./frontend/.env
          echo "API_DESTINATION=${{ secrets.FE_API_DESTINATION }}" >> ./frontend/.env
          echo "CYPRESS_BASE_URL=${{ secrets.FE_CYPRESS_BASE_URL }}" >> ./frontend/.env

      - name: Create Backend .env
        run: |
          mkdir -p ./backend
          echo "JWT_SECRET=${{ secrets.BE_JWT_SECRET }}" >> ./backend/.env
          echo "SIGN_UP_SECRET=${{ secrets.BE_SIGN_UP_SECRET }}" >> ./backend/.env
          echo "DATABASE_URL=${{ secrets.BE_DATABASE_URL }}" >> ./backend/.env
          echo "CLIENT_URL=${{ secrets.BE_CLIENT_URL }}" >> ./backend/.env
          echo "CLOUDINARY_API_KEY=${{ secrets.BE_CLOUDINARY_API_KEY }}" >> ./backend/.env
          echo "CLOUDINARY_API_SECRET=${{ secrets.BE_CLOUDINARY_API_SECRET }}" >> ./backend/.env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.BE_CLOUDINARY_CLOUD_NAME }}" >> ./backend/.env


      - name: Build and Run Docker Compose
        run: docker-compose up --build -d
