name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kiểm tra mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Tạo file .env cho frontend
      - name: Create Frontend .env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./src/frontend/.env
          echo "SIGN_UP_SECRET=${{ secrets.SIGN_UP_SECRET }}" >> ./src/frontend/.env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> ./src/frontend/.env
          echo "API_DESTINATION=${{ secrets.API_DESTINATION }}" >> ./src/frontend/.env
          echo "CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL }}" >> ./src/frontend/.env

      # Tạo file .env cho backend
      - name: Create Backend .env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./src/backend/.env
          echo "SIGN_UP_SECRET=${{ secrets.SIGN_UP_SECRET }}" >> ./src/backend/.env
          echo "DATABASE_URL=postgresql://username:password@db:5432/db" >> ./src/backend/.env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> ./src/backend/.env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> ./src/backend/.env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> ./src/backend/.env

      # Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Thiết lập Docker Compose
      - name: Set up Docker Compose
        run: |
          DB_USER=username \
          DB_PASSWORD=password \
          DB_NAME=db \
          DB_PORT=5432 \
          FE_PORT=3000 \
          BE_PORT=3123 \
          docker-compose -f src/docker-compose.yml up --build -d

      - name: Run Cypress tests
        run: |
          # Chờ một chút để các container có thể khởi động xong
          sleep 10
          # Chạy Cypress tests trong container frontend
          docker-compose -f src/docker-compose.yml exec frontend npm run cypress run

      - name: Shut down containers
        run: docker-compose -f src/docker-compose.yml down
